sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: aa6JrV0rWqVnYrRQFJIP1ITGYFdk6NL4oz1zL81vtt2L6LOiLklIgnEOpvFC2up+gWKp1ZigZ4exWaPzUusDpjGX6cjng/aaSHja+KhyzgyeBhvJklm5nKuZSH2b31iygdbPQeSFXOB2K5n03jo2c2HWk77ODzOTn4NBjPq2hUesFXZ+qvF57Cmj+fmlHnF3K9aa3blTNEzEC7hZBUp0npvF0SFDq0j7/tGzhLHb8cPjQDruWV9DfT2Nmfd+xICL6u0CW8tvViVuZY1K8fjpPNIwqlbO34lmW1tSVSnbu1PFPVMgUDgOnggEYWq3ae80iXt71UvxQl8Gi8tv/zCZixuW6rrgCXh1t203JnLx7uYzzTKF6J2pziL89wdiYh/mlluNkjpzA3SK2blF5p/1r8+9whnYMdyvaGWH2Dgf1HX+xzX+XAn8J3w3g4Mgpb6mO3e4PAYyzFCjMDq1WGWMcZQSx4nhfLPV675HUvnAfV69ltm7s8uvghG/FDr5GgTQ4fHkRr/aBWUCU/aA1J7xcuzBJfpKtNmGcpo8QwRjbAG9/AYE/r1Lld9dqqdFVgP7sJPIFKXUJTzJbWNu0Lmuar0Td2UtfFFN7xw0UaVGonVFgKRYObIxKImvcPediomkNPMICMowVm6N0sJmA0JDKePlrJgUzU9K4y+9tGTrzjM=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: PRG7H2MyHQG16Cop9h674xTQ+mZPPvyEIxqkHYmU+wnO5ekXrKnkLjGGYNmcEeqScHz3uLDw+oteUfkUQ5x0wuU0nzQjbPSTLmwtoFp42L1HaUkPQDJDNh7B+xE8NHKIYlElTOgqGNm061uFKpmXYUueeGmKRssiskZYmqWXTNHzA+7xpOGIplYhOyR+huSYM2ugdpwsKfK4FACCKNqUjN7Fzq9U9fObLOT2ChEX+jXNiHDHhLTQha7MnqJhd0kmNvynI/M7AhV7sszenD6ymPtwMjr0MaYa6q4uwTP1M+q4q4nvu5i7a8YFKJ99MskdyfawmmP3fyRO0I/O5ir3A3pyk/STu5eIg4RsKeIKEE+VWKgrSjewoELakqtd+NKIZcW91s5x4lUvGzkXTdK5AU6NcsVY4aOQXcgVNm7H2O+YNJJ6zXzE91wJbJQftgm3pm3OVVlMuvYM2pVuBq9At8Hp3cBfQzPHOw24hmvK2gvHWEoXaJ5jiGtMaa8xGZPVhqxsje4Z6A4iOzpDo+nK+X0y5xStdjHPr59uDB/vRkKYnaTl2H+5/rClJtCZSSlbtqviagRPOzQBzU5xW+Pyt7Fl2Xlk37M8D3Akno6X8mY67x8Af10n8Jouh0mMoXJGJYLJIMWTQXvKVsOiB57VI4Qv+55k8e3GWyd2yfGjWXU=
